apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    compileSdk = libs.versions.compileSdkVersion.get().toInteger()

    defaultConfig {
        applicationId "com.thewizrd.simplesleeptimer"

        testApplicationId "com.thewizrd.simplesleeptimer.test"
        // Specifies the fully-qualified class name of the test instrumentation runner.
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        // The following argument makes the Android Test Orchestrator run its
        // "pm clear" command after each test invocation. This command ensures
        // that the app's state is completely cleared between tests.
        testInstrumentationRunnerArguments clearPackageData: 'true'

        minSdkVersion 26
        targetSdkVersion libs.versions.targetSdkVersion.get().toInteger()
        // NOTE: Version Code Format [TargetSDK, Version Name, Build Number, Variant Code (Android: 0, WearOS: 1)]
        versionCode 341500031
        versionName "1.5.0"

        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            crunchPngs true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        compose true
        dataBinding true
        viewBinding true
        buildConfig true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.compose.compiler.version.get()
    }

    kotlin {
        jvmToolchain(17)
    }
    namespace 'com.thewizrd.simplesleeptimer'
}

dependencies {
    implementation project(":shared_resources")

    coreLibraryDesugaring libs.desugar.jdk.libs

    // Kotlin
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.play.services

    implementation libs.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.fragment.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.androidx.core.splashscreen
    implementation(libs.datastore)

    implementation libs.androidx.constraintlayout
    implementation libs.androidx.recyclerview
    implementation libs.material

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    implementation libs.firebase.crashlytics
    implementation libs.firebase.config

    // WearOS
    implementation libs.play.services.wearable
    compileOnly libs.wearable

    implementation libs.androidx.wear
    implementation libs.androidx.wear.ongoing
    implementation libs.androidx.wear.phone.interactions
    implementation libs.wear.remote.interactions

    // WearOS Tiles
    implementation libs.wear.tiles
    debugImplementation libs.wear.tiles.renderer
    testImplementation libs.wear.tiles.testing
    debugImplementation libs.wear.tiles.tooling
    implementation libs.wear.tiles.tooling.preview
    implementation libs.androidx.protolayout.material
    implementation libs.horologist.tiles

    // WearOS Compose
    implementation libs.androidx.activity.compose
    implementation platform(libs.compose.bom)
    implementation libs.androidx.runtime.livedata
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.animation.graphics
    implementation libs.androidx.compose.material
    implementation libs.androidx.compose.material.icons.extended
    implementation libs.lifecycle.viewmodel.compose
    implementation libs.wear.compose.foundation
    implementation libs.wear.compose.material
    implementation libs.wear.compose.navigation
    implementation libs.wear.compose.ui.tooling
    implementation libs.wear.tooling.preview

    implementation libs.accompanist.drawablepainter
    implementation libs.horologist.compose.layout
    implementation libs.horologist.compose.tools

    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.tooling

    implementation libs.timber
    implementation libs.gson
}