plugins {
    id 'com.android.application'
    id 'com.android.legacy-kapt'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

android {
    compileSdk = libs.versions.compileSdkVersion.get().toInteger()

    defaultConfig {
        applicationId "com.thewizrd.simplesleeptimer"

        testApplicationId "com.thewizrd.simplesleeptimer.test"
        // Specifies the fully-qualified class name of the test instrumentation runner.
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        // The following argument makes the Android Test Orchestrator run its
        // "pm clear" command after each test invocation. This command ensures
        // that the app's state is completely cleared between tests.
        testInstrumentationRunnerArguments clearPackageData: 'true'

        minSdkVersion libs.versions.minSdkVersion.get().toInteger()
        targetSdkVersion libs.versions.targetSdkVersion.get().toInteger()
        // NOTE: Version Code Format [TargetSDK, Version Name, Build Number, Variant Code (Android: 0, WearOS: 1)]
        // NOTE: update SUPPORTED_VERSION_CODE if needed
        versionCode 371700010
        versionName "1.7.0"

        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            crunchPngs true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig true
        resValues true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlin {
        jvmToolchain(21)
    }
    namespace 'com.thewizrd.simplesleeptimer'
}

dependencies {
    implementation project(":shared_resources")
    implementation project(":circularseekbar")

    coreLibraryDesugaring libs.desugar.jdk.libs

    // Unit Testing
    androidTestImplementation libs.test.core

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation libs.test.runner
    androidTestImplementation libs.test.rules

    // Assertions
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.truth
    androidTestImplementation libs.google.truth

    // Kotlin
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.play.services
    implementation libs.androidx.core.ktx
    implementation libs.androidx.preference.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.androidx.work.runtime.ktx

    implementation libs.play.services.wearable
    implementation libs.app.update.ktx

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    implementation libs.firebase.crashlytics
    implementation libs.firebase.config

    implementation libs.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.core.splashscreen
    implementation libs.material

    implementation libs.androidx.palette.ktx

    implementation libs.timber
    implementation libs.gson
}